---
platform: linux
image: docker:///concourse/static-golang

inputs:
- name: tracker-resource
  path: gopath/src/github.com/mrosecrance/tracker-resource

outputs:
- name: built-resource

params:
  TRACKER_TOKEN:

run:
  path: gopath/src/github.com/mrosecrance/tracker-resource/scripts/ci
